name: blog_text_env
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=2.131
  - blas-devel=3.9.0
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - contourpy=1.3.1
  - cycler=0.12.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - gensim=4.3.3
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.2
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.5.0
  - llvm-openmp=20.1.2
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - munkres=1.1.4
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.29
  - openjpeg=2.5.2
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pillow=11.1.0
  - pip=25.0
  - pybind11-abi=4
  - pyparsing=3.2.3
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - readline=8.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.0
  - six=1.17.0
  - smart_open=5.2.1
  - sqlite=3.45.3
  - statsmodels=0.14.4
  - tk=8.6.14
  - tornado=6.4.2
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
